name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/create-tag-action
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: ./build/CONTRIBUTORS.svg
      
      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.0

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: package.json info
        id: info
        uses: ./

      - run: echo "name - \x1b[32;1m ${{ steps.info.outputs.name }}\x1b[0m"
      - run: echo "version - \x1b[32;1m ${{ steps.info.outputs.version }}\x1b[0m"
      - run: echo "description - \x1b[32;1m ${{ steps.info.outputs.description }}\x1b[0m"
      - run: echo "author - \x1b[32;1m ${{ steps.info.outputs.author }}\x1b[0m"
      - run: echo "homepage - \x1b[32;1m ${{ steps.info.outputs.homepage }}\x1b[0m"
      - run: echo "license - \x1b[32;1m ${{ steps.info.outputs.license }}\x1b[0m"
      - run: echo "keywords - \x1b[32;1m ${{ steps.info.outputs.keywords }}\x1b[0m"
      - run: echo "repository - \x1b[32;1m ${{ steps.info.outputs.repository }}\x1b[0m"
      - run: echo "os - \x1b[32;1m ${{ steps.info.outputs.os }}\x1b[0m"
      - run: echo "cpu - \x1b[32;1m ${{ steps.info.outputs.cpu }}\x1b[0m"

      - name: package.json info
        id: info2
        uses: ./
        with:
          data: |
            {
              "name": "@jaywcjlove/github-action-package-test"
            }

      - run: echo "name - \x1b[32;1m ${{ steps.info2.outputs.name }}\x1b[0m"
      - run: echo "version - \x1b[32;1m ${{ steps.info2.outputs.version }}\x1b[0m"
      - run: echo "description - \x1b[32;1m ${{ steps.info2.outputs.description }}\x1b[0m"
      - run: echo "author - \x1b[32;1m ${{ steps.info2.outputs.author }}\x1b[0m"
      - run: echo "homepage - \x1b[32;1m ${{ steps.info2.outputs.homepage }}\x1b[0m"
      - run: echo "license - \x1b[32;1m ${{ steps.info2.outputs.license }}\x1b[0m"
      - run: echo "keywords - \x1b[32;1m ${{ steps.info2.outputs.keywords }}\x1b[0m"
      - run: echo "repository - \x1b[32;1m ${{ steps.info2.outputs.repository }}\x1b[0m"
      - run: echo "os - \x1b[32;1m ${{ steps.info2.outputs.os }}\x1b[0m"
      - run: echo "cpu - \x1b[32;1m ${{ steps.info2.outputs.cpu }}\x1b[0m"